global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'wordpress'
    metrics_path: /metrics
    static_configs:
      - targets: ['wordpress:80']  

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121'] 
