global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']  

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
